### ISSUE TITLE
Review - Intro to Pandas

### ISSUE THREAD

**Issue by Symsystem** [christophetrinh/ADA#3]
-- Intro to Pandas --
Ex 2 : 
Why did you invoke "data[100]" at the beginning ? When I execute this line, it makes an error.
Moreover the result you obtained with indexed_data is different than mine when I execute the code: I get only one row (the patient 1).

Ex 3 👍 : Seems very good
Ex 4: The dataframe obp_with_nan does not exist. But otherwise, good idea to rank them. The ranked result could have been sorted as well !

Ex 5 👍

Ebola exercise:
Why do you load the first 2 files of each country at the beginning of the exercise ?
Otherwise the method seems very good and concise. I did not know that we could load all the files in only one row. I personally wrote a loop to do it.
The only thing that seems not correct to me is that you only give the total of cases / deaths by country and not the DAILY total by country and date.
Good utilization of data types and data transformations !

--- Data wrangling with Pandas ---

Ex 1: Your code is very clean and works perfectly ! 👍 

Titanic:
Your code is suddenly less comments than elsewhere. So a lot of results doesn't mean something without analyzing the code.
For the last point, you could have created a plot to better see the results.
Otherwise seems good ! 👍

**Comment by christophetrinh** [comment]
Hello, thanks for the feedback, it is very useful.

-- Intro to Pandas --
Ex 2 : 
_Why did you invoke "data[100]" at the beginning ?_ 

It was a try, we forgot to remove the cell.

_Moreover the result you obtained with indexed_data is different than mine when I execute the code: I get only one row (the patient 1)._

It may because we ran after transformation on data. 

_Ex 4: The dataframe obp_with_nan does not exist. But otherwise, good idea to rank them. The ranked result could have been sorted as well !_

You're right, while cleaning the code, we forgot to rename the variable. It is actually 
_obp_base = obp_base[pd.notnull(obp_base)]._

_Ebola exercise:
Why do you load the first 2 files of each country at the beginning of the exercise ?_

We do it to visualize the data quickly, but we still had forgotten to remove these cells.

_The only thing that seems not correct to me is that you only give the total of cases / deaths by country and not the DAILY total by country and date._

Yes, you're right, we misunderstood the instructions.

_Titanic:
Your code is suddenly less comments than elsewhere. So a lot of results doesn't mean something without analyzing the code._
Yes, sorry about that. It's because we found the solution at the last moment, and we decided to push the code quickly before the deadline.
